MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 128
  DEVICE: "cuda"
DATASETS:
  TRAIN: ("M2_train",)
  TEST: ("M2_val",)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  MAX_ITER: 10000
OUTPUT_DIR: "/scratch/rl4789/CellClassif/models/M2"
VERSION: 2